/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studioproject;

import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author niebz
 */
public class P2 extends javax.swing.JFrame {

    /**
     * Creates new form P2
     */
    public P2() {
        initComponents();

        String sql = "select stu_id,timeout_latest from room where status='f' ";
        try {
            ResultSet rs = new conn().getResultSet( sql );
            while(rs.next()) {
                String stu_id = rs.getString(1);
                String time_out_st = rs.getString(2);

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                LocalDateTime time_out = LocalDateTime.parse(time_out_st,formatter);
                LocalDateTime now = LocalDateTime.now();
                if ( time_out.compareTo( now ) <=0 ){
                    sql = String.format( "update room set status='t' where stu_id='%s'",stu_id );
                    if ( new conn().execute( sql ) ) System.out.println(String.format( "Studio %s change status to t",stu_id ));
                    else System.out.println("Cannot change status");
                }else System.out.println(String.format( "Studio %s is using",stu_id));
            }
        }catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        small_btn = new javax.swing.JButton();
        medium_btn = new javax.swing.JButton();
        large_btn = new javax.swing.JButton();
        his_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(383, 100));

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel4.setText("Select Studio Size");

        small_btn.setText("Small 250฿/hr.");
        small_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                small_btnActionPerformed(evt);
            }
        });

        medium_btn.setText("Medium 450฿/hr.");
        medium_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medium_btnActionPerformed(evt);
            }
        });

        large_btn.setText("Large 550฿/hr.");
        large_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                large_btnActionPerformed(evt);
            }
        });

        his_btn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        his_btn.setText("History");
        his_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                his_btnActionPerformed(evt);
            }
        });

        exit_btn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(his_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(small_btn)
                        .addGap(10, 10, 10)
                        .addComponent(medium_btn)
                        .addGap(10, 10, 10)
                        .addComponent(large_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(his_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit_btn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(small_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medium_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(large_btn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static String size,stu_id;
    private void small_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_small_btnActionPerformed
        // TODO add your handling code here:

        String sql = "select stu_id from room where size='small' and status='t'";
        try {
            ResultSet rs = new conn().getResultSet( sql );
            if ( rs.next() ) {
                stu_id = rs.getString( 1 );
                size = "small";
                this.setVisible(false);
                new P3().setVisible(true);
            }else {
                JOptionPane.showMessageDialog( this,"Studio is fully","Notice",JOptionPane.WARNING_MESSAGE );
            }
        }catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_small_btnActionPerformed

    private void medium_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medium_btnActionPerformed
        // TODO add your handling code here:

        String sql = "select stu_id from room where size='medium' and status='t'";
        try {
            ResultSet rs = new conn().getResultSet( sql );
            if ( rs.next() ) {
                stu_id = rs.getString( 1 );
                size = "medium";
                this.setVisible(false);
                new P3().setVisible(true);
            }else {
                JOptionPane.showMessageDialog( this,"Studio is fully","Notice",JOptionPane.WARNING_MESSAGE );
            }
        }catch (Exception ex) {
            ex.printStackTrace();
        }



    }//GEN-LAST:event_medium_btnActionPerformed

    private void large_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_large_btnActionPerformed
        // TODO add your handling code here:

        String sql = "select stu_id from room where size='large' and status='t'";
        try {
            ResultSet rs = new conn().getResultSet( sql );
            if ( rs.next() ) {
                stu_id = rs.getString( 1 );
                size = "large";
                this.setVisible(false);
                new P3().setVisible(true);
            }else {
                JOptionPane.showMessageDialog( this,"Studio is fully","Notice",JOptionPane.WARNING_MESSAGE );
            }
        }catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_large_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new P1().setVisible(true);
    }//GEN-LAST:event_exit_btnActionPerformed

    private void his_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_his_btnActionPerformed
        // TODO add your handling code here:
        new His( this,false ).setVisible( true );
    }//GEN-LAST:event_his_btnActionPerformed

    public static String getStuSize(){
        return size;
    }

    public static String getStuId(){
        return stu_id;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit_btn;
    private javax.swing.JButton his_btn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton large_btn;
    private javax.swing.JButton medium_btn;
    private javax.swing.JButton small_btn;
    // End of variables declaration//GEN-END:variables
}
